### ISSUE TITLE
Build failed - The system cannot find the file specified

### ISSUE THREAD

**Issue by J-Korn** [OpenRedButtonProject/orb#317]
**_Android Studio Iguana | 2023.2.1 Patch 2
Android Gradle Plugin Version : 7.4.2
Gradle Version 7.5_**

While trying to build any of the apps in the project I'm met with the following error:

`CMake Error at CMakeLists.txt:21 (add_library):
    Cannot find source file:
          src/main/symlink.mock_dial_service/url_lib.c
          Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
    .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc`

This seems to be the relevant part but I am happy to provide the full error stack in case it is helpful.

**Comment by giorgos-epitropou-obs** [comment]
Hi, I am assuming you are building the mockapps for the emulator. How did you upgrade the gradle version(s)? I used the AGP assistant (and ticked all the available options,  **both** the upgrade and the post-upgrade options). Then I built the project (also did a clean + rebuild due to previous 4.2.2 artifacts) by selecting to run an app (e.g 'Launch mitexperts') on a TV(720) API 30 virtual device I am currently using and tested video playback from the available streaming tests,

Also I am attaching the generated diff after the upgrade. You can check if you got the same changes
[diff.txt](https://github.com/user-attachments/files/15612506/diff.txt)
